import { Router, Request, Response } from "express";
import axios from "axios";
import { YoutubeTranscript } from "youtube-transcript";
import { parseCaptionXml, parseCaptionJson3 } from "../utils/captionUtils";

const router = Router();

const DEFAULT_HEADERS = {
  "user-agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "accept-language": "en-US,en;q=0.9",
};

const YT_WEB_API_KEY =
  process.env.YT_WEB_PLAYER_API_KEY || "AIzaSyA-CPZ5r_L6O7m1qfqCBKOnYwH5crcRc9g";
const YT_WEB_CLIENT_VERSION =
  process.env.YT_WEB_CLIENT_VERSION || "2.20240111.08.00";
const YT_WEB_CLIENT_NAME = process.env.YT_WEB_CLIENT_NAME || "WEB";

function trackLabel(t: any): string {
  // Try to display a human-friendly name
  if (t?.name?.simpleText) return t.name.simpleText;
  if (Array.isArray(t?.name?.runs)) {
    return t.name.runs.map((r: any) => r?.text ?? "").join("");
  }
  return t?.languageName ?? t?.languageCode ?? "Unknown";
}

function chooseTrack(tracks: any[], lang?: string, preferASR?: boolean) {
  if (!Array.isArray(tracks) || tracks.length === 0) return null;

  const norm = (s: string) => s?.toLowerCase?.() ?? s;

  let candidates = tracks;

  if (lang) {
    const exact = candidates.find((t) => norm(t.languageCode) === norm(lang));
    if (exact) candidates = [exact];
    else {
      const prefix = candidates.find((t) =>
        norm(t.languageCode)?.startsWith(norm(lang))
      );
      if (prefix) candidates = [prefix];
    }
  }

  // Prefer non-ASR (human) unless caller explicitly wants autogenerated.
  if (preferASR) {
    const asr = candidates.find((t) => t.kind === "asr");
    if (asr) return asr;
  } else {
    const human = candidates.find((t) => t.kind !== "asr");
    if (human) return human;
  }

  return candidates[0] ?? tracks[0];
}

router.get("/scrape", async (req: Request, res: Response): Promise<void> => {
  const videoId = (req.query.id as string)?.trim();
  const lang = (req.query.lang as string | undefined)?.trim();
  const preferAuto = req.query.autogen === "1";

  if (!videoId) {
    res.status(400).json({ error: "Missing video ID" });
    return;
  }

  const recordFailure = (source: string, err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`⚠️ ${source} transcript fetch failed:`, message);
    return `${source}: ${message}`;
  };

  let availableCaptions: { name: string; languageCode: string; isAutoGenerated?: boolean }[] = [];
  let isAutoGenerated = false;
  let lastError: string | undefined;

  const cookie = process.env.YT_CONSENT_COOKIE; // optional (some regions still require it)
  const headerCookie = cookie ? { cookie } : {};

  const fetchPlayerCaptions = async () => {
    try {
      const body = {
        context: {
          client: {
            clientName: YT_WEB_CLIENT_NAME,
            clientVersion: YT_WEB_CLIENT_VERSION,
            hl: "en",
            gl: "US",
          },
        },
        videoId,
      };

      const response = await axios.post(
        `https://www.youtube.com/youtubei/v1/player?key=${YT_WEB_API_KEY}`,
        body,
        {
          headers: {
            ...DEFAULT_HEADERS,
            ...headerCookie,
            referer: "https://www.youtube.com/",
            "content-type": "application/json",
          },
          timeout: 15000,
          validateStatus: () => true,
        }
      );

      if (response.status >= 400) {
        lastError = `player api status ${response.status}`;
        return { track: null, trackList: [] as any[] };
      }

      const data: any = response.data ?? {};
      const tracklist =
        data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

      availableCaptions = tracklist.map((t: any) => ({
        name: trackLabel(t),
        languageCode: t.languageCode,
        isAutoGenerated: t.kind === "asr",
      }));

      if (!tracklist.length) {
        lastError = "player api returned no caption tracks";
        return { track: null, trackList: [] as any[] };
      }

      const track = chooseTrack(tracklist, lang, preferAuto);
      if (!track?.baseUrl) {
        lastError = "player api track missing baseUrl";
        return { track: null, trackList: tracklist };
      }

      isAutoGenerated = track.kind === "asr";
      return { track, trackList: tracklist };
    } catch (err) {
      lastError = recordFailure("player api", err);
      return { track: null, trackList: [] as any[] };
    }
  };

  const fetchFromTrack = async (track: any) => {
    const ensureLang = (url: URL) => {
      if (!url.searchParams.has("lang") && track?.languageCode) {
        url.searchParams.set("lang", track.languageCode);
      }
      if (lang && lang !== track?.languageCode) {
        url.searchParams.set("tlang", lang);
      }
    };

    try {
      const jsonUrl = new URL(track.baseUrl);
      jsonUrl.searchParams.set("fmt", "json3");
      ensureLang(jsonUrl);

      const jsonResp = await axios.get(jsonUrl.toString(), {
        headers: {
          ...DEFAULT_HEADERS,
          referer: "https://www.youtube.com/",
        },
        responseType: "json",
        timeout: 15000,
        validateStatus: () => true,
      });

      if (jsonResp.status < 400) {
        const parsed = parseCaptionJson3(jsonResp.data);
        if (parsed.length) {
          return parsed;
        }
        lastError = "json3 response contained no timed text";
      } else {
        lastError = `json3 status ${jsonResp.status}`;
      }
    } catch (err) {
      lastError = recordFailure("json3", err);
    }

    try {
      const xmlUrl = new URL(track.baseUrl);
      ensureLang(xmlUrl);

      const xmlResp = await axios.get<string>(xmlUrl.toString(), {
        headers: {
          ...DEFAULT_HEADERS,
          referer: "https://www.youtube.com/",
        },
        responseType: "text",
        timeout: 15000,
        validateStatus: () => true,
      });

      if (xmlResp.status < 400) {
        const parsed = parseCaptionXml(xmlResp.data);
        if (parsed.length) {
          return parsed;
        }
        lastError = "xml response contained no timed text";
      } else {
        lastError = `xml status ${xmlResp.status}`;
      }
    } catch (err) {
      lastError = recordFailure("xml", err);
    }

    return [] as ReturnType<typeof parseCaptionXml>;
  };

  const fetchWithLibrary = async () => {
    try {
      const options: Record<string, string> = {};
      if (lang) options.lang = lang;
      const segments = await YoutubeTranscript.fetchTranscript(videoId, options);
      const parsed = segments
        .map((segment) => ({
          start: Number(segment.offset) || 0,
          duration: Number(segment.duration) || 1.5,
          text: segment.text?.trim?.() ?? "",
        }))
        .filter((segment) => segment.text);

      if (parsed.length) {
        availableCaptions = [
          {
            name: "Auto (library)",
            languageCode: options.lang || "auto",
            isAutoGenerated: true,
          },
        ];
        isAutoGenerated = true;
        return parsed;
      }

      lastError = "library response contained no timed text";
    } catch (err) {
      lastError = recordFailure("library", err);
    }

    return [];
  };

  const fetchFromSiteFallback = async () => {
    try {
      const fallbackUrl = new URL(
        `https://youtubetranscript.com/?server_vid2=${encodeURIComponent(videoId)}`
      );
      if (lang) fallbackUrl.searchParams.set("lang", lang);

      const fallbackResp = await axios.get(fallbackUrl.toString(), {
        headers: {
          ...DEFAULT_HEADERS,
          referer: "https://youtubetranscript.com/",
        },
        responseType: "json",
        timeout: 15000,
        validateStatus: () => true,
      });

      if (fallbackResp.status >= 400) {
        lastError = `fallback status ${fallbackResp.status}`;
        return [];
      }

      if (!Array.isArray(fallbackResp.data)) {
        const summary =
          typeof fallbackResp.data === "string"
            ? fallbackResp.data.slice(0, 120)
            : JSON.stringify(fallbackResp.data).slice(0, 120);
        lastError = `fallback unexpected payload: ${summary}`;
        console.warn("⚠️ fallback returned unexpected payload", fallbackResp.data);
        return [];
      }

      const parsed = fallbackResp.data
        .map((item: any) => ({
          start: Number(item.start) || 0,
          duration: Number(item.duration) || 1.5,
          text: typeof item.text === "string" ? item.text.trim() : "",
        }))
        .filter((line: any) => line.text);

      if (parsed.length) {
        availableCaptions = [
          {
            name: "Auto (fallback)",
            languageCode: lang || "auto",
            isAutoGenerated: true,
          },
        ];
        isAutoGenerated = true;
        return parsed;
      }

      lastError = "fallback response contained no timed text";
    } catch (err) {
      lastError = recordFailure("fallback", err);
    }

    return [];
  };

  try {
    const { track } = await fetchPlayerCaptions();

    let transcript: ReturnType<typeof parseCaptionXml> = [];

    if (track) {
      transcript = await fetchFromTrack(track);
    }

    if (!transcript.length) {
      transcript = await fetchWithLibrary();
    }

    if (!transcript.length) {
      transcript = await fetchFromSiteFallback();
    }

    if (!transcript.length) {
      const status = availableCaptions.length ? 502 : 404;
      res.status(status).json({
        error:
          status === 404
            ? "No captions are available for this video."
            : "Caption sources were found but returned no timed text.",
        details: lastError || "All caption sources failed",
      });
      return;
    }

    res.status(200).json({
      transcript,
      captions: availableCaptions,
      isAutoGenerated,
    });
  } catch (err: any) {
    console.error("❌ Transcript fetch error:", err?.message || err);
    res.status(502).json({
      error: "Failed to fetch transcript",
      details: err?.message || String(err),
    });
  }
});

export default router;
